// File generated by FlutterFire CLI.
// Temporarily commented out as Firebase is disabled in favor of offline local notifications.
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwW0vB7fEcxirSlKNOXK1E2lF8AK-JPz4',
    appId: '1:250000519124:android:7eaaad430529af1b36b041',
    messagingSenderId: '250000519124',
    projectId: 'rimrid-sasthoseba',
    storageBucket: 'rimrid-sasthoseba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSDH0b5taCakN8SMx7ftjiOtDcHrSs3s',
    appId: '1:250000519124:ios:9cf1764d8b412e5136b041',
    messagingSenderId: '250000519124',
    projectId: 'rimrid-sasthoseba',
    storageBucket: 'rimrid-sasthoseba.firebasestorage.app',
    iosBundleId: 'com.example.rimridSasthoseba',
  );
}
*/
